### ISSUE TITLE
Add Windows Server support

### ISSUE THREAD

**Issue by edmael** [fbocolowski/sssm#1]
Hello,
the project looks very promising, it would be nice to also have a command to monitor a Windows Server.

I _think_ you can add your script by using WSL, but it's not the best way to monitor a server.

I can do some testing if needed.

**Comment by fbocolowski** [comment]
Can you test WLS and how it works so far?
For Windows Server support we need to create either an application or a PowerShell script that does the same as http://sssm.ml/runner.sh does. Any suggestion?

**Comment by edmael** [comment]
Just tried with WSL and it works, but a "native" solution would be better.

As soon as I have some time on my hands I'll try and check that script, will update this bug report if I manage to do something useful.
