### ISSUE TITLE
Roadmap for alerting?

### ISSUE THREAD

**Issue by benyanke** [fbocolowski/sssm#31]
Is there any sort of notification / alerting on the roadmap? So far I really like what I see here!

**Comment by fbocolowski** [comment]
With notification/alerting you mean triggers for specific events? Such as "server down" and "ram/disk usage limits"?

Is so, i'll be developing these for Slack only and release it in the next 2-3 days and it's over Issue #9 =)
If any suggestions and ideas head over to it and leve a comment!

**Comment by benyanke** [comment]
Exactly what I'm thinking. Would love to see email or webhook notifications too but that's another discussion for another day, after the slack implementation is done and finely tuned.
