### ISSUE TITLE
Add triggers notification for events

### ISSUE THREAD

**Issue by fbocolowski** [fbocolowski/sssm#9]
Allow user to set up a trigger for event. example:
When 80% of RAM - Send Slack
When 90% of Disk - Send Email

**Comment by fbocolowski** [comment]
Also alert when server is down for N minutes.

**Comment by benyanke** [comment]
Would also love this.

**Comment by benyanke** [comment]
I'd also like to propose that the notification interface be created in a generic way, so later more notification "plugins" could be added.

**Comment by fbocolowski** [comment]
Just released the first version of triggers. Please give it a try! I'll be trying them on the next days to test and see if I can find improvements to make.

Slack and outgoing Webhook available.

**Comment by fbocolowski** [comment]
Closed issue and waiting feedbacks!
